# Generated by Django 5.0.3 on 2024-03-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('aplicacion', models.CharField(max_length=100)),
                ('nombreSV', models.CharField(max_length=20)),
                ('estadoApp', models.CharField(max_length=20)),
                ('ipV4', models.CharField(max_length=50)),
                ('estadoipV4', models.CharField(max_length=50)),
                ('ambienteSV', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=100)),
                ('so', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacion', models.CharField(max_length=100)),
                ('nombreSV', models.CharField(max_length=20)),
                ('IP', models.CharField(max_length=50)),
                ('SO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lineabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('aplicacion', models.CharField(max_length=200)),
                ('instancia', models.CharField(max_length=100)),
                ('ambienteSV', models.CharField(max_length=50)),
                ('nombreSVHost', models.CharField(max_length=50)),
                ('nombreSVOVM', models.CharField(max_length=50)),
                ('ipV4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='llave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAppCMDB', models.CharField(max_length=100)),
                ('nombreAppEventos', models.CharField(max_length=100)),
                ('nombrAppLB', models.CharField(max_length=100)),
            ],
        ),
    ]
