# Generated by Django 5.0.3 on 2024-03-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('nombreSV', models.CharField(max_length=100)),
            ],
        ),
    ]
