# Generated by Django 5.0.3 on 2024-03-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero_GSI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMDBvsEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacion', models.CharField(max_length=100)),
                ('ambienteSV', models.CharField(max_length=100)),
                ('estadoAppCMDB', models.CharField(max_length=100)),
                ('nombreSVCMDB', models.CharField(max_length=100)),
                ('nombreSVEventos', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cmdbvseventos',
                'managed': False,
            },
        ),
    ]
