# Generated by Django 5.0.3 on 2024-03-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablero_GSI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aplicacion',
            new_name='Aplicaciones',
        ),
    ]
