# Generated by Django 5.0.3 on 2024-03-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero_GSI', '0002_cmdbvseventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineabasevsEventos',
            fields=[
                ('aplicacion', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ambienteSV', models.CharField(max_length=100)),
                ('nombreSVLB', models.CharField(max_length=100)),
                ('nombreSVEventos', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lineabasevseventos',
                'managed': False,
            },
        ),
    ]
