# Generated by Django 5.0.3 on 2024-03-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero_GSI', '0002_rename_aplicacion_aplicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='lineabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
